name: 'poc1'





services:

  proxy:
    image: 'docker.io/nginx:1.28.0-alpine-slim'
    networks:
      lan: {}
    ports:
      - 8080:8080/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  keycloak:
    image: 'quay.io/keycloak/keycloak:26.2.1-0'
    networks:
      lan: {}
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: '/auth/'
      KC_PROXY_HEADERS: 'xforwarded'
      KC_HTTP_ENABLED: 'true'
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

#  backend:
#    image: 'poc1-be:1.0.0'
#    networks:
#      lan: {}
#    environment:
#       AUTH_INTROSPECTION_ENDPOINT: "http://localhost:8080/auth/realms/poc/protocol/openid-connect/token/introspect"
#       AUTH_CLIENT_ID: "private"
#       AUTH_CLIENT_SECRET: "VaSyUQksKSDf1Suv1lLVrmxaRQNaczHW"
#       CORS_ORIGIN: "http://localhost:4200"
#    build:
#      context: ./poc1-backend/
#
#  frontend:
#    image: 'poc1-fe:1.0.0'
#    networks:
#      lan: {}
#    build:
#      context: ./poc1-frontend/





networks:
  lan:
    driver: bridge
    name: 'poc1'